#####################################################################################################
#####                 NSPanel Easy - https://github.com/edwardtfn/NSPanel-Easy                  #####
#####################################################################################################
##### ESPHOME ADD-ON - ESPECTRE WITH BLUETOOTH PROXY                                            #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
##### ESPectre co-existence with Bluetooth.                                                     #####
#####################################################################################################
---
esp32:
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP_COEX_SW_COEXIST_ENABLE: n

bluetooth_proxy:
  active: false

esp32_ble_tracker:
  software_coexistence: false
  scan_parameters:
    interval: 100ms
    window: 5ms
    duration: 5min
    continuous: false
    active: true

espectre:
  segmentation_window_size_ms: 1000
  evaluation_interval_ms: 250

packages:
  espectre_package: !include nspanel_esphome_addon_espectre.yaml
  bluetooth_package: !include nspanel_esphome_addon_bluetooth.yaml
...
